spring.application.name=demo
server.port=8000

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/loginmock
spring.datasource.username=root
spring.datasource.password=0429
spring.jpa.hibernate.ddl-auto=update
# ? ?? ? update? ??

# JWT ??
loginmock.jwtSecret=mySecretKey_must_be_long_enough_for_HS512_algorithm
loginmock.jwtExpirationMs=86400000
# 24???? ??


# Redis
spring.session.store-type=redis
spring.redis.host=localhost
spring.redis.port=6379


